Repository jkpark104/JS_Mini_Project, pull requests merged in 2021-10, with the labels that each got.

#16 Feature/combine each html
  CSS/base.css
  CSS/cardFlip.css
  CSS/icon.css
  CSS/minesweeper.css
  CSS/style_park.css
  JS/cardFlip.js
  JS/icon.js
  JS/js_park.js
  JS/main.mjs
  JS/state.js
  color-game.html
  index.html
Labels: bug

#21 Feature/color game apply js
  CSS/base.css
  CSS/style_park.css
  JS/icon.js
  JS/js_park.js
  JS/js_park.mjs
  JS/main.mjs
  JS/state.mjs
  color-game.html
  index.html
Labels: bug, enhancement

#22 feat: Update MineSweeper to Show All Mines
  CSS/minesweeper.css
  JS/minesweeper.mjs
  index.html
Labels: enhancement

#27 design: Modify margin about minesweeper And hover text Style
  CSS/hover.css
  CSS/minesweeper.css
  CSS/reset.css
  main.html
  minesweeper.html
Labels: enhancement

#31 refactor: Refactor showAllGameBoard Function
  JS/minesweeper.mjs
Labels: bug

#35 refactor: Add handleGameOver function & Modify handleRigt/leftClick f…
  CSS/minesweeper.css
  JS/minesweeper.mjs
Labels: bug

#36 fix: Modify main page
  CSS/cardFlip.css
  CSS/hover.css
  CSS/main.css
  JS/cardFlip.js
  JS/cardFlip.mjs
  cardFlip.html
  main.html
  music/CardFlip.mp3
  music/loseCardFlip.mp3
  music/winCardFlip.mp3
Labels: bug

#43 design: Modify game-container width and height to 200px
  CSS/main.css
  JS/cardFlip.mjs
  JS/changeMainColor.js
  JS/minesweeper.mjs
  cardFlip.html
  color-game.html
  images/colorguess.gif
  index.html
  minesweeper.html
Labels: bug

#44 feat: Add sound_effect on color_game
  JS/cardFlip.mjs
  JS/changeMainColor.mjs
  JS/color_game.mjs
  JS/main.mjs
  JS/minesweeper.mjs
Labels: enhancement

#47 Update README.md
  README.md
Labels: documentation
